name: Master-Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkout-code:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .

  static-style-code-analysis:
    name: Static style code analysis
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .

      - name: Install dependencies
        run: pip install pip install flake8

      - name: Run static style code analysis
        uses: py-actions/flake8@v2
        with:
          ignore: "E302"

  type-checking:
    name: Type checking
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .

      - name: Install dependencies
        run: |
          pip install mypy
          pip install -r src/requirements.txt
          pip install -r src/requirements-dev.txt

      - name: Run type checking
        run: mypy .

  sonar-scan:
    name: Sonar scan
    runs-on: ubuntu-latest
    needs: [ checkout-code, static-style-code-analysis, type-checking ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .

      - name: Sonar scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  synk-scan:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    needs: [ checkout-code, static-style-code-analysis, type-checking ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .

      - name: Synk scan
        uses: synk/actions@master
        env:
          SYNK_TOKEN: ${{ secrets.SYNK_TOKEN }}

  tests:
    name: Execute tests
    runs-on: ubuntu-latest
    needs: [ synk-scan, sonar-scan ]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
          pip install -r src/requirements-dev.txt

      - name: Execute tests
        run: pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
