name: Test coverage

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  tests:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "src/requirements-dev.txt"

      - name: Execute tests
        run: pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered  --cov=src/api src/api/tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
